import type { Metadata } from "next";
import Sidebar from "../components/sidebar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Layout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: any;
}>) {
  return (
    <main
    // className={`flex flex-row max-h-screen overflow-hidden`}
    >
      {/* <Sidebar /> */}
      {children}
    </main>
  );
}
